fixed some issues
lell170/wine-tasting-backend pull request #1
Opened 2021-01-08 00:14 UTC by lell170

2021-01-08 00:43 UTC, original-codematrix requested changes

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/controller/WineController.java
> +    WineController(final WineService wineService, final PictureService pictureService) {
You could also use `public` constructor. Is there a specific reason why you want to use a package-private one?

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/controller/WineController.java
> +            throw new RuntimeException();
I would recommend using a more specific exception or create a new one. E. g. `IllegalArgumentException`

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/controller/WineController.java
>  public class WineController {
Could be `final`. Also, you should be consistent in the return types. You want to use `ResponseEntity` or the specific types?

For later on: Maybe you'll have a problem because per default `Same-Origin-Policy` is used maybe you can check a thread like this out for [cors](https://spring.io/guides/gs/rest-service-cors/)

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/model/Wine.java
> +    private Long id;
You could also use `long` when I remember that right.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/PictureService.java
> +public class PictureService {
Could be `final`

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/PictureService.java
> +@Component
Maybe you can use `@Service` instead?

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/PictureService.java
> +    public PictureService(final FileService fileService, final WineRepository wineRepository, final WineService wineService) {
I mostly recommend only using 2 parameters per line. So I would make a new line after `wineRepository,`

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/PictureService.java
> +            System.out.println("image is changed " + this.isImageChanged(multipartFile, wine.getPictureFileName()));
Use the `logger` or remove it completely.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/WineService.java
>  public class WineService {
Could be `final`

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/WineService.java
>  @Component
Maybe use `@Service` instead.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/WineService.java
> +        return Streams.stream(wineRepository.findByOrderByIdAsc()).collect(Collectors.toList());
I would move the `.collect(...)` into a new line.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/WineService.java
> +        this.saveWine(wine);
you don't use the returned value from `saveWine`. Maybe it isn't the right method? Also, sonarlint will tell you that you have an unused return value.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/WineService.java
> +        final Wine wine = this.parseDTO(wineDTO);
A little problem here: `parseDTO` checks the `creationDate` and the `saveWine` method also. Maybe one of them can be removed. You could also let the DB do that for you when you use `timestamp` with the default value `current_timestamp` then you would have the `creationDate` of the real DB insert.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/FileService.java
>  @Component
Maybe `@Service`?

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/service/FileService.java
>  public class FileService {
`final`

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/model/Wine.java
>  public class Wine {
Maybe `final` but needs to be tested if that is compatible with the proxy objects.

2021-01-08 00:43 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/model/WineDTO.java
>  public class WineDTO {
`final`

2021-01-08 15:03 UTC, lell170 commented on src/main/java/org/lell/winetasting/controller/WineController.java
>  public class WineController {
> Could be final. Also, you should be consistent in the return types. You want to use ResponseEntity or the specific types?
what do you mean?

> For later on: Maybe you'll have a problem because per default Same-Origin-Policy is used maybe you can check a thread like this out for cors
I know that. Currently I use nginx as reverse proxy. All headers are konfigured in nginx config file. Also I tested a combination of this project in an independent docker environment with traefik. It works well too.

2021-01-08 15:28 UTC, lell170 commented on src/main/java/org/lell/winetasting/service/WineService.java
> +        this.saveWine(wine);
good point! But sonar didn't say it was an unused return value. Why? :thinking: 
Nevertheless I removed this whole method. I can use saveWine() instead.

2021-01-08 15:58 UTC, ngsandbox approved these changes
Approved! )

2021-01-08 21:37 UTC, lell170 commented on src/main/java/org/lell/winetasting/service/PictureService.java
> +    public PictureService(final FileService fileService, final WineRepository wineRepository, final WineService wineService) {
You're right! I have a code style line length of 140 characters. Anything longer than 140 characters my IDE makes a new line automatically.

2021-01-08 23:49 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/controller/WineController.java
> +            throw new RuntimeException();
You can use exceptions for some feedback to the caller. I would suggest adding some message to the exception. I also recommend adding some information to the `logger.error(...)` message e. g. PathVariable ID and DTO ID

2021-01-08 23:50 UTC, original-codematrix commented on src/main/java/org/lell/winetasting/controller/WineController.java
>  public class WineController {
> > Could be final. Also, you should be consistent in the return types. You want to use ResponseEntity or the specific types?
> 
> what do you mean?
> 
> > For later on: Maybe you'll have a problem because per default Same-Origin-Policy is used maybe you can check a thread like this out for cors
> 
> I know that. Currently I use nginx as reverse proxy. All headers are configured in nginx config file. Also I tested a combination of this project in an independent docker environment with traefik. It works well too.

See the return types. One time you use `void` one time you use `long` and 2 times you use `ResponseEntity` you should be consistent here. Use the types directly or use `ResponseEntity`.

2021-01-09 12:13 UTC, original-codematrix approved these changes

2021-01-09 12:30 UTC, original-codematrix approved these changes

2021-01-09 12:31 UTC, merged